### ISSUE TITLE
Path shortening not working since fixing the telescope.path deprecated error

### ISSUE THREAD

**Issue by rmagatti** [rmagatti/session-lens#12]
I need to actually understand how to build custom entry_makers.

<img width="636" alt="Screen Shot 2021-07-15 at 2 34 17 AM" src="https://user-images.githubusercontent.com/2881382/125756476-f628829d-a068-4cc4-a149-365c513f6d02.png">

**Comment by prncss-xyz** [comment]
Also, if it could use telescope extention api ( `require('telescope').load_extension 'session-lens' ` etc) it would be much helpful.

**Comment by rmagatti** [comment]
@prncss-xyz that should work fine actually 😅 are you seeing something different?
