### ISSUE TITLE
[Feature request] Change neovim's directory when opening a session

### ISSUE THREAD

**Issue by akinsho** [rmagatti/session-lens#28]
Hi 👋🏿 ,

When using this plugin to switch between projects selecting a session restores that session in the current directory which means that if in project `a` with it's set of files and I then use this plugin to open `b` whilst still with nvim's directory in project `a` it opens all the files for `b` and then overrides the session for `a` with the files for `b`.

Ideally instead of doing this opening a session would also change vims directory so that the autosave functionality will save to project's b's directory not `a`

Hopefully this makes sense

**Comment by rmagatti** [comment]
Hey 👋, something seems off with the explanation, the saved session file should contain the `cwd` of that particular session, so when switching with this plugin all we're doing is
```lua
    AutoSession.AutoSaveSession() -- Save current session
    vim.cmd("%bd!") -- Delete all buffers
    AutoSession.RestoreSession(selection.path) -- Restore the selected session (with its own cwd)
```

Maybe the `cwd` of the selected session was initially saved incorrectly? Does this happen with every session switch? This is an example of one of my session files.
<img width="688" alt="Screen Shot 2022-07-04 at 5 55 16 PM" src="https://user-images.githubusercontent.com/2881382/177226476-a5830c41-77ac-4d37-9b59-0d29512ddc90.png">

**Comment by akinsho** [comment]
Checked my sessions and that line is present but I also had a *lot* of old sessions piled up so I did a tidy up and things seem to work better, so I'll close this out now
