### ISSUE TITLE
Feature: Enable toggling between last selected session

### ISSUE THREAD

**Issue by sergiornelas** [rmagatti/session-lens#31]
When you are switching between two sessions continuously, would be amazing if you can toggle with the last selected session using a shortcut instead of typing the session name again and again.

That's the only feature I need in order to get rid of tmux.

Thank you for your work!

**Comment by rmagatti** [comment]
Hey @sergiornelas, this does sound like a good idea!

**Comment by rmagatti** [comment]
@sergiornelas this is being worked on in this PR. Essentially I'll be merging session-lens functionality straight into auto-session in the near future, which should include toggling between the two most recent sessions. The linked PR is still a work in progress so I do not recommend trying it out for the toggling feature, if you'd like to try it out for regular session switching to prepare for the addition of session-lens into auto-session feel free to do so.
https://github.com/rmagatti/auto-session/pull/161
