### ISSUE TITLE
Error restoring session! The session might be corrupted.

### ISSUE THREAD

**Issue by tmpm697** [rmagatti/session-lens#35]
I go this error when try to use `session-lens`:
```
:Telescope session-lens search_session
error:          Error restoring session! The session might be corrupted.
        Disabling auto save. Please check for errors in your config. Error:
Press ENTER or type command to continue
      Vim(unlet):E108: No such variable: "SessionLoad"
```
happens with v0.8.2 and nighly

**Comment by rmagatti** [comment]
Something is corrupted with your session. `SessionLoad` is something the `mksession` command (what auto-session uses under the hood) creates in your .vim session file. This error doesn't come from session-lens, it comes from trying to load your `.vim` session file. You can confirm that by running `source ~/path/to/your/session-file.vim`.

**Comment by tmpm697** [comment]
in what event i can have a corrupted file session, i use auto-session and session-lens.

**Comment by rmagatti** [comment]
Impossible to tell without more information. You can try deleting your session and starting fresh to see if the error continues or goes away. Also, these plugins have debug modes you can enable for more information.
