### ISSUE TITLE
Switching sessions quits without saving the former session

### ISSUE THREAD

**Issue by brunofavs** [rmagatti/session-lens#45]
Hey,

I'm using autosession in conjunction with session lens.

I usually hop between 2 sessions in my workflow.

I'm having the issue that when I switch it quits the first one without saving and opens the second one and sometimes I'm not paying attention and loose work.

Is there a way to implement a safety check before switching from a non saved session?

Like "Do you wish to save before switching?"

I would also be happy with a hook as well. That way I could just prompt it to do :wa before switching

Thank you in advance, both your plugins are amazing, this is just a small annoyance really.

**Comment by rmagatti** [comment]
Hey @brunofavs `auto-session` already includes `session-lens`. Try uninstalling `session-lens` and using the code provided in `auto-session` already. Hopefully that makes things work. This repo will be archived soon to avoid confusion.

**Comment by brunofavs** [comment]
I only installed auto-session, I never had session-lens standalone installed, I saw it was a session-lens issue so I posted here. It was actually my bad I didn't notice this repo was archived.
