### ISSUE TITLE
Respect auto-save setting from auto-session

### ISSUE THREAD

**Issue by pettni** [rmagatti/session-lens#5]
Hello,

Thanks for your work on the session plugins!

One thing that confused me when setting it up was that sessions are auto-saved by the session-lens switcher. It might be more intuitive if that only happens when  ```auto_session_enabled = true``` or ```auto_save_enabled = true```

Cheers

**Comment by rmagatti** [comment]
Hey yeah this should be an easy change since SessionLens has access to those configs from AutoSession already, I'll see if I can do it around weekend time. Thanks for the issue submission!

**Comment by rmagatti** [comment]
@pettni, the change is in. Let me know if that doesn't do it for some reason!

**Comment by pettni** [comment]
That was quick and it works great! This will help keep the session list uncluttered.

Thanks again for your work on the session plugins!
